language: python
python:
  - "2.7"

# command to install dependencies
#install: "pip install -r requirements.txt"
sudo: required

services:
  - docker

before_install:
  - docker build -t oz_control:operation_zombie image/

install:
  - docker run -d -p 80:80 oz_control:operation_zombie
# command to run tests
script: #nosetests
  - docker ps | grep -q oz_control
  - curl $(docker-machine ip):80


