language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
#install: "pip install -r requirements.txt"
sudo: required

services:
  - docker

before_install:
  - docker build -t oz_control:operation_zombie images/

install:
  - docker run -d -p 80:80 oz_control:operation_zombie
# command to run tests
script: #nosetests
  - docker ps | grep -q oz_control


