language: python
python:
  - "2.7"

# command to install dependencies
#install: "pip install -r requirements.txt"
sudo: required

services:
  - docker

before_install:
  - docker build -t laynecsmall/opzom_control image/

install:
  - docker run -d -p 80:80 --name ozc laynecsmall/opzom_control
# command to run tests
script: 
  - docker ps | grep -q opzom_control
  - docker exec ozc python /srv/scripts/can_fetch_page.py http://localhost

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push laynecsmall/opzom_control

notifications:
  slack:
    rooms:
      - undeadbaby:$SLACK_KEY#random
